### ISSUE TITLE
Rust naming convention

### ISSUE THREAD

**Issue by hellow554** [SilensAngelusNex/pgraph#5]
https://github.com/SilensAngelusNex/pgraph/blob/83b7c2fe554f3bdd5c754cb1c15e649c73f3fcd4/src/id.rs#L30

In rust you don't normally use `get_*` but only `*` instead, e.g. not `get_gen`, but only `gen`, same for `get_index` -> `index`.

If you have a `pub foo(&self)` and `pub foo_mut(&mut self)` function, you can make the member `foo` `pub` by itself, is has no advantage over the other.

https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#getter/setter-methods-[rfc-344]

**Comment by regexident** [comment]
Similarly `fn get(&self, …)` would be more idiomatic as `fn vertex(&self, …)` and `fn get_data(&self, …)` as `fn vertex_data(&self, …)`.
